version: "3.8"
services:
  skybridge:
    container_name: "skybridge"
    image: videah/skybridge:latest
    restart: always
    volumes:
      - skybridge:/app/database
    environment:
      # Base URL of where SkyBridge will be hosted without the protocol.
      - SKYBRIDGE_BASEURL=skybridge-emwxpw.fly.dev
      # Random secret, generate with `openssl rand -base64 32`.
      - SKYBRIDGE_SECRET=5KVaSox30bQjC5/ydyMNg+E+TNNpZv1Q5R/yLB1SScQ=
      # Password used to make a SkyBridge instance private.
      - SKYBRIDGE_AUTH_PASSWORD=dSN0B2wMJrcsmQjDH5pSC2rflX6Zb3XZ7gVrt/wSqjc=
      # Should a bridge password be required to authenticate?
      - SKYBRIDGE_REQUIRE_AUTH_PASSWORD=true
      # Should a nice index page be shown on the root URL?
      - SKYBRIDGE_SHOW_INDEX=true
      # Allow backfilling/scrolling on timelines? (can cause issues on instances under heavy load)
      - SKYBRIDGE_ALLOW_BACKFILL=true

volumes:
  skybridge:
